# Generated by Django 5.2 on 2026-04-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('attack', models.PositiveIntegerField(default=70)),
                ('defense', models.PositiveIntegerField(default=70)),
                ('overall', models.PositiveIntegerField(default=70)),
                ('continent', models.CharField(blank=True, choices=[('SOUTH_AMERICA', 'América do Sul'), ('NORTH_AMERICA', 'América do Norte'), ('EUROPE', 'Europa'), ('AFRICA', 'África'), ('ASIA', 'Ásia'), ('OCEANIA', 'Oceania')], max_length=20)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='groups.group')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
                'ordering': ['name'],
            },
        ),
    ]
